/**
 * 高考基础题 + 平时作业题语料（从公开资料归纳的典型基础题）
 * 来源类型：教材作业 / 高考基础练 / 一轮复习小题
 * 仅收录可用本地引擎验证的「基础」题，不含压轴综合。
 */
export const GAOKAO_BASIC_CORPUS = [
  // ── 立体几何：度量 ──
  {
    id: 'geo-vol-1',
    subject: 'geometry',
    source: '作业·正方体体积',
    text: '正方体棱长为2，求体积',
    expect: { answerIncludes: ['8'] },
  },
  {
    id: 'geo-vol-2',
    subject: 'geometry',
    source: '作业·正方体体积',
    text: '正方体棱长为5，求体积',
    expect: { answerIncludes: ['125'] },
  },
  {
    id: 'geo-diag-1',
    subject: 'geometry',
    source: '作业·体对角线',
    text: '正方体棱长为2，求体对角线的长度',
    expect: { answerIncludes: ['√3', '2√3'] },
  },
  {
    id: 'geo-surf-1',
    subject: 'geometry',
    source: '作业·表面积',
    text: '正方体棱长为3，求表面积',
    expect: { answerIncludes: ['54'] },
  },
  {
    id: 'geo-sphere-1',
    subject: 'geometry',
    source: '作业·球体',
    text: '球体半径为3，求体积',
    expect: { answerIncludes: ['36', 'π'] },
  },
  {
    id: 'geo-cuboid-1',
    subject: 'geometry',
    source: '作业·长方体',
    text: '长方体长3、宽4、高5，求体积',
    expect: { answerIncludes: ['60'] },
  },

  // ── 立体几何：线面角 / 点面距离（高考基础） ──
  {
    id: 'geo-lpa-1',
    subject: 'geometry',
    source: '高考基础·线面角',
    text: '正方体ABCD-A₁B₁C₁D₁中，求A₁B与平面ABCD所成角的正弦值',
    expect: { answerIncludes: ['√2/2'] },
  },
  {
    id: 'geo-lpa-2',
    subject: 'geometry',
    source: '高考基础·线面角',
    text: '正方体棱长为2，求对角线A₁C与底面ABCD所成角的正弦值',
    expect: { answerIncludes: ['√3/3'] },
  },
  {
    id: 'geo-lpa-3',
    subject: 'geometry',
    source: '高考基础·线面角',
    text: '正方体中，求直线A₁C与平面ABCD所成角的正切值',
    expect: { answerIncludes: ['tanθ', '√2'] },
  },
  {
    id: 'geo-dist-1',
    subject: 'geometry',
    source: '高考基础·点面距离',
    text: '正方体棱长为3，求点C₁到平面ABCD的距离',
    expect: { answerIncludes: ['3'] },
  },
  {
    id: 'geo-dist-2',
    subject: 'geometry',
    source: '作业·点面距离',
    text: '正方体ABCD-A1B1C1D1棱长为4，求点B1到平面ABCD的距离',
    expect: { answerIncludes: ['4'] },
  },

  // ── 导数 ──
  {
    id: 'deriv-poly-1',
    subject: 'derivative',
    source: '作业·多项式求导',
    text: '求 f(x)=x³−3x 的导数',
    expect: { answerIncludes: ['3x²', '−3', '-3'] },
  },
  {
    id: 'deriv-poly-2',
    subject: 'derivative',
    source: '作业·二次求导',
    text: '求 f(x)=2x²+3x−1 的导数',
    expect: { answerIncludes: ['4x', '3'] },
  },
  {
    id: 'deriv-tan-1',
    subject: 'derivative',
    source: '高考基础·切线',
    text: '求曲线 y=x³−3x 在 x=1 处的切线方程',
    expect: { answerIncludes: ['−2', '-2'] },
  },
  {
    id: 'deriv-tan-2',
    subject: 'derivative',
    source: '作业·切线',
    text: '求曲线 y=x^3 在 x=2 处的切线方程',
    expect: { answerIncludes: ['12'] },
  },
  {
    id: 'deriv-tan-3',
    subject: 'derivative',
    source: '作业·切线 y=x²',
    text: '已知曲线 y=x²，求点(1,1)处的切线方程',
    expect: { answerIncludes: ['2'] },
  },
  {
    id: 'deriv-ext-1',
    subject: 'derivative',
    source: '高考基础·极值',
    text: '求函数 f(x)=x³−3x 的极值',
    expect: { answerIncludes: ['2'] },
  },
  {
    id: 'deriv-mono-1',
    subject: 'derivative',
    source: '作业·单调性',
    text: '求函数 f(x)=x³−3x 的单调区间',
    expect: { answerIncludes: ['增', '减', '−1', '-1', '1'] },
  },

  // ── 圆锥曲线 ──
  {
    id: 'conic-e-1',
    subject: 'conic',
    source: '高考基础·椭圆离心率',
    text: '椭圆 x²/25+y²/16=1 的离心率',
    expect: { answerIncludes: ['3/5', '0.6'] },
  },
  {
    id: 'conic-f-1',
    subject: 'conic',
    source: '高考基础·椭圆焦点',
    text: '椭圆 x²/25+y²/16=1 的焦点坐标',
    expect: { answerIncludes: ['±3', '3'] },
  },
  {
    id: 'conic-hf-1',
    subject: 'conic',
    source: '高考基础·双曲线焦点',
    text: '双曲线 x²/9−y²/16=1 的焦点坐标',
    expect: { answerIncludes: ['±5', '5'] },
  },
  {
    id: 'conic-p-1',
    subject: 'conic',
    source: '作业·抛物线焦点',
    text: '抛物线 y²=8x 的焦点坐标',
    expect: { answerIncludes: ['(2,0)', '2'] },
  },
  {
    id: 'conic-p-2',
    subject: 'conic',
    source: '作业·抛物线准线',
    text: '抛物线 y²=8x 的准线方程',
    expect: { answerIncludes: ['x=', '-2'] },
  },
  {
    id: 'conic-c-1',
    subject: 'conic',
    source: '作业·圆的配方',
    text: '圆 x²+y²−4x+6y−3=0 的圆心与半径',
    expect: { answerIncludes: ['2', '−3', '-3', '4'] },
  },
  {
    id: 'conic-e-2',
    subject: 'conic',
    source: '作业·椭圆',
    text: '求椭圆 x²/9+y²/4=1 的离心率',
    expect: { answerIncludes: ['√5/3', '5'] },
  },

  // ── 排列组合 / 概率 ──
  {
    id: 'combo-p-1',
    subject: 'combo',
    source: '作业·分步乘法',
    text: '从6人选正、副组长各1人，有多少种选法？',
    expect: { answerIncludes: ['30'] },
  },
  {
    id: 'combo-c-1',
    subject: 'combo',
    source: '作业·组合',
    text: '从5人中选2人当代表，有多少种选法？',
    expect: { answerIncludes: ['10'] },
  },
  {
    id: 'combo-c-2',
    subject: 'combo',
    source: '作业·组合',
    text: '从8个不同元素中取出3个，有多少种选法？',
    expect: { answerIncludes: ['56'] },
  },
  {
    id: 'prob-1',
    subject: 'combo',
    source: '作业·古典概率',
    text: '袋中有3红2白，不放回连抽2次都是红的概率',
    expect: { answerIncludes: ['3/10'] },
  },
  {
    id: 'prob-2',
    subject: 'combo',
    source: '高考基础·古典概率',
    text: '袋中有4红3白，不放回抽2次，求先红后白的概率',
    expect: { answerIncludes: ['2/7'] },
  },
  {
    id: 'prob-3',
    subject: 'combo',
    source: '作业·有放回',
    text: '袋中有3红2白，有放回抽2次，求两次都是红的概率',
    expect: { answerIncludes: ['9/25'] },
  },
  {
    id: 'prob-4',
    subject: 'combo',
    source: '作业·对立事件',
    text: '袋中有3红2白，不放回抽2次，求至少有一红的概率',
    expect: { answerIncludes: ['9/10'] },
  },
  {
    id: 'combo-add-1',
    subject: 'combo',
    source: '作业·加法原理',
    text: '甲班30人乙班20人，从两班中选1名代表，有多少种选法',
    expect: { answerIncludes: ['50'] },
  },
  {
    id: 'combo-mult-1',
    subject: 'combo',
    source: '作业·乘法原理',
    text: '有3种上衣、4种裤子，各选一件搭配，有多少种选法',
    expect: { answerIncludes: ['12'] },
  },

  // ── 扩充：作业 / 高考基础常见变式 ──
  {
    id: 'geo-vol-3',
    subject: 'geometry',
    source: '作业·正方体体积',
    text: '正方体棱长为4，求体积',
    expect: { answerIncludes: ['64'] },
  },
  {
    id: 'geo-surf-2',
    subject: 'geometry',
    source: '作业·正方体表面积',
    text: '正方体棱长为6，求表面积',
    expect: { answerIncludes: ['216'] },
  },
  {
    id: 'geo-diag-2',
    subject: 'geometry',
    source: '作业·体对角线',
    text: '正方体棱长为3，求体对角线的长度',
    expect: { answerIncludes: ['3√3', '√3'] },
  },
  {
    id: 'geo-cyl-1',
    subject: 'geometry',
    source: '作业·圆柱体积',
    text: '圆柱底面半径为2，高为5，求体积',
    expect: { answerIncludes: ['20', 'π'] },
  },
  {
    id: 'geo-cone-1',
    subject: 'geometry',
    source: '作业·圆锥体积',
    text: '圆锥底面半径为3，高为4，求体积',
    expect: { answerIncludes: ['12', 'π'] },
  },
  {
    id: 'geo-lpa-4',
    subject: 'geometry',
    source: '高考基础·线面角',
    text: '正方体ABCD-A1B1C1D1中，求AB1与平面ABCD所成角的正切值',
    expect: { answerIncludes: ['tanθ', '1'] },
  },
  {
    id: 'geo-dih-1',
    subject: 'geometry',
    source: '高考基础·二面角',
    text: '正方体ABCD-A₁B₁C₁D₁中，求二面角A₁-BC-A的平面角的正切值',
    expect: { answerIncludes: ['tan', '√2', '1'] },
  },
  {
    id: 'deriv-poly-3',
    subject: 'derivative',
    source: '作业·多项式求导',
    text: '求 f(x)=x^3+2x 的导数',
    expect: { answerIncludes: ['3x', '2'] },
  },
  {
    id: 'deriv-tan-4',
    subject: 'derivative',
    source: '作业·切线',
    text: '求曲线 y=x^2 在 x=3 处的切线方程',
    expect: { answerIncludes: ['6'] },
  },
  {
    id: 'deriv-tan-5',
    subject: 'derivative',
    source: '高考基础·切线点斜',
    text: '已知曲线 y=x³，求点(1,1)处的切线方程',
    expect: { answerIncludes: ['3'] },
  },
  {
    id: 'conic-e-3',
    subject: 'conic',
    source: '作业·椭圆离心率',
    text: '椭圆 x²/16+y²/9=1 的离心率',
    expect: { answerIncludes: ['√7/4', '7'] },
  },
  {
    id: 'conic-p-3',
    subject: 'conic',
    source: '作业·抛物线焦点',
    text: '抛物线 y²=12x 的焦点坐标',
    expect: { answerIncludes: ['(3,0)', '3'] },
  },
  {
    id: 'prob-5',
    subject: 'combo',
    source: '作业·古典概率',
    text: '袋中有5红3白，不放回抽2次都是红的概率',
    expect: { answerIncludes: ['5/14'] },
  },
  {
    id: 'prob-6',
    subject: 'combo',
    source: '高考基础·至少一红',
    text: '袋中有4红2白，不放回抽2次，求至少有一红的概率',
    expect: { answerIncludes: ['14/15', '1'] },
  },
  {
    id: 'combo-p-2',
    subject: 'combo',
    source: '作业·排列',
    text: '从5人选班长、学习委员、体育委员各1人，有多少种选法？',
    expect: { answerIncludes: ['60'] },
  },
  {
    id: 'combo-c-3',
    subject: 'combo',
    source: '作业·组合',
    text: '从7人中选3人参加比赛，有多少种选法？',
    expect: { answerIncludes: ['35'] },
  },
]
