// ═══════════════════════════════════════════════════════
//  Constants — 几何维度 · Clean data, no emoji
// ═══════════════════════════════════════════════════════


export const PRICING_PLANS = [
  {
    id: 'free',
    name: '免费版',
    subtitle: '永久免费',
    price: 0,
    period: '',
    description: '先体验方法动画，再升级无限理解',
    highlight: '样例不限次 · 自有题每日 8 次',
    features: [
      { text: '方法动画样例', detail: '运动学 / 力学 / 几何 / 导数等不占额度' },
      { text: '每日 8 次自有题', detail: '粘贴自己的题开始理解' },
      { text: '分步讲解', detail: '选题型 → 列公式 → 代入' },
      { text: '3D / 动画演示', detail: '看清速度、力、空间关系' },
      { text: '历史记录', detail: '本地保存最近题目' },
      { text: '题目分享', detail: '链接分享给同学' },
    ],
    limitations: [],
    cta: '免费开始',
    popular: false,
    color: 'var(--text-secondary)',
    bgGradient: 'var(--bg-surface)',
    icon: '📐',
  },
  {
    id: 'pro',
    name: 'Pro 会员',
    subtitle: '学生常用',
    price: 29,
    period: '/月',
    description: '无限理解 · 课堂导出 · 错题闭环',
    highlight: '买的是理解效率，不是答案',
    features: [
      { text: '无限额度', detail: '取消每日题目限制', star: true },
      { text: '方法动画全开', detail: '物理 / 数学专题持续演示', star: true },
      { text: 'PPT 课件导出', detail: '一键生成课堂 PPT', star: true },
      { text: '错题本', detail: '自动收集 · 分类管理', star: true },
      { text: '学习分析', detail: '薄弱方法 · 掌握度' },
      { text: 'PDF / 高清图导出', detail: '讲义与截图' },
      { text: '云端同步', detail: '多设备历史记录' },
    ],
    limitations: [],
    cta: '升级 Pro',
    popular: true,
    color: 'var(--accent)',
    bgGradient: 'linear-gradient(135deg, rgba(15,107,92,0.08) 0%, rgba(196,69,54,0.04) 100%)',
    icon: '⭐',
    stripePriceId: 'pro_monthly',
    stripeYearlyId: 'pro_yearly',
  },
  {
    id: 'teacher',
    name: '教师版',
    subtitle: '课堂教学',
    price: 99,
    period: '/学期',
    description: 'Pro 全部功能 + 班级课件工具',
    highlight: '投影演示 · 批量 PPT · 班级统计',
    features: [
      { text: 'Pro 全部功能', detail: '无限额度 + 方法动画 + 导出' },
      { text: '批量导出 PPT', detail: '整章课件一键导出', star: true },
      { text: '班级管理', detail: '创建班级 · 邀请学生', star: true },
      { text: '学生学习统计', detail: '薄弱方法看板' },
      { text: '作业布置', detail: '在线布置 · 跟练方法' },
    ],
    limitations: [],
    cta: '升级教师版',
    popular: false,
    color: 'var(--color-success)',
    bgGradient: 'linear-gradient(135deg, rgba(34,197,94,0.05) 0%, rgba(16,185,129,0.03) 100%)',
    icon: '🏫',
    stripePriceId: 'teacher_monthly',
    stripeYearlyId: 'teacher_yearly',
  },
]

export const GEOMETRY_NAMES = {
  cube: '正方体',
  sphere: '球体',
  cylinder: '圆柱体',
  cone: '圆锥体',
  pyramid: '棱锥',
  prism: '棱柱',
  squareFrustum: '四棱台',
  circularFrustum: '圆台',
  cuboid: '长方体',
  tetrahedron: '正四面体',
  octahedron: '正八面体',
}

export const SUBJECTS = [
  {
    id: 'math',
    name: '数学',
    shortName: '数',
    icon: 'math',
    color: '#4A90E2',
    gradient: 'linear-gradient(135deg, #4A90E2, #6BA3E8)',
    description: '立体几何、函数、代数',
    features: ['AI解析', '3D动态讲解', '分步解题', '错题本'],
    path: '/math',
  },
  {
    id: 'physics',
    name: '物理',
    shortName: '物',
    icon: 'physics',
    color: '#00B4D8',
    gradient: 'linear-gradient(135deg, #00B4D8, #0096C7)',
    description: '力学、电磁学，光学',
    features: ['模型识别', '公式推导', '受力分析', '图像分析'],
    path: '/physics',
  },
]
