// ═══════════════════════════════════════════════════════
//  Constants — 几何维度 · Clean data, no emoji
// ═══════════════════════════════════════════════════════

export const EXAMPLES = [
  // ═══════════════════════════════════════════════════════
  //  必修二 · 正方体/长方体
  // ═══════════════════════════════════════════════════════
  {
    id: 'ex1',
    title: '正方体异面直线夹角',
    category: '必修二',
    text: '正方体ABCD-EFGH棱长为2，求异面直线AB与B\'D的夹角。',
    geometryType: 'cube',
    params: { size: 2 },
  },
  {
    id: 'ex2',
    title: '正方体体对角线',
    category: '必修二',
    text: '正方体棱长为2，求体对角线AG的长度。',
    geometryType: 'cube',
    params: { size: 2 },
  },
  {
    id: 'ex3',
    title: '长方体体对角线',
    category: '必修二',
    text: '长方体长3、宽4、高12，求体对角线的长度。',
    geometryType: 'cuboid',
    params: { size: 12 },
  },
  {
    id: 'ex4',
    title: '正方体面对角线夹角',
    category: '必修二',
    text: '正方体ABCD-A₁B₁C₁D₁棱长为1，求面对角线AC与BC₁所成角的余弦值。',
    geometryType: 'cube',
    params: { size: 1 },
  },
  {
    id: 'ex5',
    title: '正方体二面角',
    category: '必修二',
    text: '正方体ABCD-A₁B₁C₁D₁棱长为2，求平面A₁BD与平面ABCD所成二面角的余弦值。',
    geometryType: 'cube',
    params: { size: 2 },
  },
  {
    id: 'ex6',
    title: '正方体线面角',
    category: '必修二',
    text: '正方体ABCD-A₁B₁C₁D₁棱长为1，求直线B₁D与平面ABCD所成角的正弦值。',
    geometryType: 'cube',
    params: { size: 1 },
  },
  {
    id: 'ex7',
    title: '正方体点面距离',
    category: '必修二',
    text: '正方体ABCD-A₁B₁C₁D₁棱长为2，求点C到平面A₁BD的距离。',
    geometryType: 'cube',
    params: { size: 2 },
  },
  {
    id: 'ex8',
    title: '正方体截面积',
    category: '必修二',
    text: '正方体ABCD-A₁B₁C₁D₁棱长为4，过点A、C、D₁作截面，求截面面积。',
    geometryType: 'cube',
    params: { size: 4 },
  },
  {
    id: 'ex9',
    title: '正方体内接球',
    category: '必修二',
    text: '正方体棱长为6，求其内切球的半径和体积。',
    geometryType: 'cube',
    params: { size: 6 },
  },
  {
    id: 'ex10',
    title: '正方体外接球',
    category: '必修二',
    text: '正方体ABCD-EFGH棱长为3，求其外接球的半径和表面积。',
    geometryType: 'cube',
    params: { size: 3 },
  },

  // ═══════════════════════════════════════════════════════
  //  必修二 · 棱锥/棱柱
  // ═══════════════════════════════════════════════════════
  {
    id: 'ex11',
    title: '正四棱锥体积',
    category: '必修二',
    text: '正四棱锥P-ABCD，底面正方形边长为4，高为6，求该棱锥的体积。',
    geometryType: 'pyramid',
    params: { size: 4 },
  },
  {
    id: 'ex12',
    title: '正四棱锥侧面积',
    category: '必修二',
    text: '正四棱锥P-ABCD，底面边长2，侧棱长3，求侧面积。',
    geometryType: 'pyramid',
    params: { size: 2 },
  },
  {
    id: 'ex13',
    title: '正四棱锥斜高',
    category: '必修二',
    text: '正四棱锥底面边长为6，高为4，求斜高和侧棱长。',
    geometryType: 'pyramid',
    params: { size: 6 },
  },
  {
    id: 'ex14',
    title: '三棱柱体积',
    category: '必修二',
    text: '正三棱柱ABC-A\'B\'C\'底面边长为2，侧棱长为3，求该三棱柱的体积。',
    geometryType: 'prism',
    params: { size: 2 },
  },
  {
    id: 'ex15',
    title: '三棱柱侧棱与底面夹角',
    category: '必修二',
    text: '三棱柱ABC-A\'B\'C\'中，底面是边长为1的正三角形，侧棱长为2，求侧棱与底面所成角。',
    geometryType: 'prism',
    params: { size: 1 },
  },

  // ═══════════════════════════════════════════════════════
  //  必修二 · 旋转体
  // ═══════════════════════════════════════════════════════
  {
    id: 'ex16',
    title: '圆柱截面面积',
    category: '必修二',
    text: '圆柱底面半径为2，高为4，过上下底面圆心作轴截面，求截面面积。',
    geometryType: 'cylinder',
    params: { size: 2 },
  },
  {
    id: 'ex17',
    title: '圆柱侧面积与体积',
    category: '必修二',
    text: '圆柱底面半径为5，高为10，求圆柱的侧面积和体积。',
    geometryType: 'cylinder',
    params: { size: 5 },
  },
  {
    id: 'ex18',
    title: '球体体积与表面积',
    category: '必修二',
    text: '已知球体半径为3，求它的体积和表面积。',
    geometryType: 'sphere',
    params: { size: 3 },
  },
  {
    id: 'ex19',
    title: '球体内接正方体',
    category: '必修二',
    text: '球体内接一个正方体，球半径为3，求正方体的棱长。',
    geometryType: 'sphere',
    params: { size: 3 },
  },
  {
    id: 'ex20',
    title: '圆锥体积与母线',
    category: '必修二',
    text: '圆锥底面半径为3，高为4，求圆锥的体积和母线长度。',
    geometryType: 'cone',
    params: { size: 3 },
  },
  {
    id: 'ex21',
    title: '圆锥侧面积',
    category: '必修二',
    text: '圆锥底面半径为6，母线长为10，求圆锥的侧面积和表面积。',
    geometryType: 'cone',
    params: { size: 6 },
  },
  {
    id: 'ex22',
    title: '圆锥侧面展开图',
    category: '必修二',
    text: '圆锥底面半径为2，母线长为6，求侧面展开图扇形的圆心角。',
    geometryType: 'cone',
    params: { size: 2 },
  },
  {
    id: 'ex23',
    title: '圆台体积',
    category: '必修二',
    text: '圆台上底面半径3，下底面半径5，高为4，求圆台的体积。',
    geometryType: 'circularFrustum',
    params: { size: 5 },
  },
  {
    id: 'ex24',
    title: '圆台母线',
    category: '必修二',
    text: '圆台上底面半径2，下底面半径6，高为3，求圆台的母线长。',
    geometryType: 'circularFrustum',
    params: { size: 6 },
  },

  // ═══════════════════════════════════════════════════════
  //  拓展 · 综合题型
  // ═══════════════════════════════════════════════════════
  {
    id: 'ex25',
    title: '四棱台体积',
    category: '拓展',
    text: '四棱台上底面边长2，下底面边长4，高为3，求该棱台的体积。',
    geometryType: 'squareFrustum',
    params: { size: 4 },
  },
  {
    id: 'ex26',
    title: '长方体面对角线',
    category: '拓展',
    text: '长方体ABCD-A₁B₁C₁D₁中，AB=3，BC=4，AA₁=5，求面对角线A₁C₁的长度。',
    geometryType: 'cuboid',
    params: { size: 5 },
  },
  {
    id: 'ex27',
    title: '正方体两平面夹角',
    category: '拓展',
    text: '正方体ABCD-A₁B₁C₁D₁棱长为1，求平面AB₁D₁与平面A₁BC₁的夹角余弦值。',
    geometryType: 'cube',
    params: { size: 1 },
  },
  {
    id: 'ex28',
    title: '圆锥内接球',
    category: '拓展',
    text: '圆锥底面半径为4，高为3，在其内部放置一个最大的球，求球的半径。',
    geometryType: 'cone',
    params: { size: 4 },
  },
  {
    id: 'ex29',
    title: '圆柱内接长方体',
    category: '拓展',
    text: '圆柱底面半径为5，高为8，求其内接长方体的最大体积。',
    geometryType: 'cylinder',
    params: { size: 5 },
  },
  {
    id: 'ex30',
    title: '正四棱锥外接球',
    category: '拓展',
    text: '正四棱锥P-ABCD底面边长为2，高为3，求其外接球的半径。',
    geometryType: 'pyramid',
    params: { size: 2 },
  },
  {
    id: 'ex31',
    title: '正方体截面周长',
    category: '拓展',
    text: '正方体ABCD-A₁B₁C₁D₁棱长为4，过A₁、B、D三点作截面，求截面三角形的周长。',
    geometryType: 'cube',
    params: { size: 4 },
  },
  {
    id: 'ex32',
    title: '球冠体积',
    category: '拓展',
    text: '球体半径为5，用一个距球心3的平面截球，求球冠的体积。',
    geometryType: 'sphere',
    params: { size: 5 },
  },

  // ═══════════════════════════════════════════════════════
  //  拓展 · 正四面体
  // ═══════════════════════════════════════════════════════
  {
    id: 'ex33',
    title: '正四面体体积',
    category: '拓展',
    text: '正四面体ABCD棱长为6，求它的体积。',
    geometryType: 'tetrahedron',
    params: { size: 6 },
  },
  {
    id: 'ex34',
    title: '正四面体表面积',
    category: '拓展',
    text: '正四面体棱长为4，求它的表面积。',
    geometryType: 'tetrahedron',
    params: { size: 4 },
  },
  {
    id: 'ex35',
    title: '正四面体高',
    category: '拓展',
    text: '正四面体ABCD棱长为3，求顶点A到底面BCD的高。',
    geometryType: 'tetrahedron',
    params: { size: 3 },
  },
  {
    id: 'ex36',
    title: '正四面体外接球',
    category: '拓展',
    text: '正四面体ABCD棱长为2，求它的外接球半径。',
    geometryType: 'tetrahedron',
    params: { size: 2 },
  },
  {
    id: 'ex37',
    title: '正四面体内切球',
    category: '拓展',
    text: '正四面体棱长为3，求它的内切球半径。',
    geometryType: 'tetrahedron',
    params: { size: 3 },
  },
  {
    id: 'ex38',
    title: '正四面体对棱距离',
    category: '拓展',
    text: '正四面体ABCD棱长为2，求对棱AB与CD之间的距离。',
    geometryType: 'tetrahedron',
    params: { size: 2 },
  },

  // ═══════════════════════════════════════════════════════
  //  拓展 · 正八面体
  // ═══════════════════════════════════════════════════════
  {
    id: 'ex39',
    title: '正八面体体积',
    category: '拓展',
    text: '正八面体棱长为3，求它的体积。',
    geometryType: 'octahedron',
    params: { size: 3 },
  },
  {
    id: 'ex40',
    title: '正八面体表面积',
    category: '拓展',
    text: '正八面体棱长为2，求它的表面积。',
    geometryType: 'octahedron',
    params: { size: 2 },
  },
  {
    id: 'ex41',
    title: '正八面体体对角线',
    category: '拓展',
    text: '正八面体棱长为4，求它的体对角线长（对顶点距离）。',
    geometryType: 'octahedron',
    params: { size: 4 },
  },
  {
    id: 'ex42',
    title: '正八面体截面',
    category: '拓展',
    text: '正八面体棱长为2，过赤道四边形作截面，求截面面积。',
    geometryType: 'octahedron',
    params: { size: 2 },
  },
]

export const PRICING_PLANS = [
  {
    id: 'free',
    name: '免费版',
    subtitle: '永久免费',
    price: 0,
    period: '',
    description: 'AI 立体几何学习工作台',
    highlight: '学生第一次使用就能完整解决问题',
    features: [
      { text: 'AI 解析题目', detail: '智能识别几何题型' },
      { text: '3D 图形生成', detail: '所有几何体类型' },
      { text: '分步讲解', detail: '完整解题过程' },
      { text: '历史记录', detail: '本地保存 50 条' },
      { text: '题目分享', detail: '链接分享给同学' },
      { text: '基础模型切换', detail: '11 种几何体自由切换' },
      { text: '每日 50 题额度', detail: '满足日常学习需求' },
    ],
    limitations: [],
    cta: '免费开始',
    popular: false,
    color: 'var(--text-secondary)',
    bgGradient: 'linear-gradient(135deg, #f8f9fb 0%, #eef0f5 100%)',
    icon: '📐',
  },
  {
    id: 'pro',
    name: 'Pro 会员',
    subtitle: '支持开发者',
    price: 19,
    period: '/月',
    description: '解锁高级学习工具 · 无限额度',
    highlight: '不是买答案，是支持产品持续开发',
    features: [
      { text: '无限额度', detail: '取消每日题目限制', star: true },
      { text: '高级教师模式', detail: '自动讲课 · 自动播放步骤 · 自动高亮重点 · 自动生成讲稿', star: true },
      { text: 'PPT 课件导出', detail: '一键生成课堂 PPT' },
      { text: 'PDF 讲义导出', detail: '精美排版讲义' },
      { text: '高清图片导出', detail: '2x 分辨率截图' },
      { text: '错题本', detail: '自动收集 · 分类管理 · 收藏题目', star: true },
      { text: '学习分析', detail: '学习时长 · 薄弱环节 · 掌握度统计', star: true },
      { text: '高级分享', detail: '分享完整工作台 · 3D 场景 · 教师讲解模式' },
      { text: '云端同步', detail: '多设备历史记录同步' },
    ],
    limitations: [],
    cta: '升级 Pro',
    popular: true,
    color: 'var(--accent)',
    bgGradient: 'linear-gradient(135deg, rgba(99,102,241,0.06) 0%, rgba(139,92,246,0.04) 100%)',
    icon: '⭐',
    stripePriceId: 'pro_monthly',
    stripeYearlyId: 'pro_yearly',
  },
  {
    id: 'teacher',
    name: '教师版',
    subtitle: '课堂教学工具',
    price: 29,
    period: '/月',
    description: 'Pro 全部功能 + 班级管理',
    highlight: '批量课件 · 学生管理 · 教学统计',
    features: [
      { text: 'Pro 全部功能', detail: '无限额度 + 所有高级工具' },
      { text: '班级管理', detail: '创建班级 · 邀请学生 · 批量管理', star: true },
      { text: '批量生成课件', detail: '一次生成全班讲义', star: true },
      { text: '批量导出 PPT', detail: '整章课件一键导出' },
      { text: '学生学习统计', detail: '全班学习数据仪表盘' },
      { text: '学生分析', detail: '个体薄弱点 · 进步曲线' },
      { text: '作业布置', detail: '在线布置 · 自动批改' },
    ],
    limitations: [],
    cta: '升级教师版',
    popular: false,
    color: 'var(--color-success)',
    bgGradient: 'linear-gradient(135deg, rgba(34,197,94,0.05) 0%, rgba(16,185,129,0.03) 100%)',
    icon: '🏫',
    stripePriceId: 'teacher_monthly',
    stripeYearlyId: 'teacher_yearly',
  },
]

export const GEOMETRY_NAMES = {
  cube: '正方体',
  sphere: '球体',
  cylinder: '圆柱体',
  cone: '圆锥体',
  pyramid: '棱锥',
  prism: '棱柱',
  squareFrustum: '四棱台',
  circularFrustum: '圆台',
  cuboid: '长方体',
  tetrahedron: '正四面体',
  octahedron: '正八面体',
}

export const GEOMETRIES = [
  { id: 'cube', name: '正方体' },
  { id: 'sphere', name: '球体' },
  { id: 'cylinder', name: '圆柱体' },
  { id: 'cone', name: '圆锥体' },
  { id: 'pyramid', name: '棱锥' },
  { id: 'prism', name: '棱柱' },
  { id: 'squareFrustum', name: '四棱台' },
  { id: 'circularFrustum', name: '圆台' },
  { id: 'cuboid', name: '长方体' },
  { id: 'tetrahedron', name: '正四面体' },
  { id: 'octahedron', name: '正八面体' },
]

export const FORMULAS = {
  cube: { volume: 'V = a³', surface: 'S = 6a²' },
  sphere: { volume: 'V = (4/3)πr³', surface: 'S = 4πr²' },
  cylinder: { volume: 'V = πr²h', surface: 'S = 2πr(r+h)' },
  cone: { volume: 'V = (1/3)πr²h', surface: 'S = πr(r+l)' },
  pyramid: { volume: 'V = (1/3)a²h', surface: 'S = a² + 2a√(h²+(a/2)²)' },
  prism: { volume: 'V = (1/2)a²h', surface: 'S = (3+√2)a²' },
  squareFrustum: { volume: 'V = h/3·(S₁+S₂+√(S₁S₂))', surface: 'S = S₁+S₂+2(a+b)√(h²+((a-b)/2)²)' },
  circularFrustum: { volume: 'V = πh/3·(R²+r²+Rr)', surface: 'S = π(R+r)l+π(R²+r²)' },
  cuboid: { volume: 'V = abc', surface: 'S = 2(ab+bc+ac)' },
  tetrahedron: { volume: 'V = a³√2/12', surface: 'S = √3·a²' },
  octahedron: { volume: 'V = a³√2/3', surface: 'S = 2√3·a²' },
}
