// ═══════════════════════════════════════════════════════
//  Constants — 几何维度 · Clean data, no emoji
// ═══════════════════════════════════════════════════════


export const PRICING_PLANS = [
  {
    id: 'free',
    name: '免费版',
    subtitle: '永久免费',
    price: 0,
    period: '',
    description: 'AI 立体几何学习工作台',
    highlight: '学生第一次使用就能完整解决问题',
    features: [
      { text: 'AI 解析题目', detail: '智能识别几何题型' },
      { text: '3D 图形生成', detail: '所有几何体类型' },
      { text: '分步讲解', detail: '完整解题过程' },
      { text: '历史记录', detail: '本地保存 50 条' },
      { text: '题目分享', detail: '链接分享给同学' },
      { text: '基础模型切换', detail: '11 种几何体自由切换' },
      { text: '每日 50 题额度', detail: '满足日常学习需求' },
    ],
    limitations: [],
    cta: '免费开始',
    popular: false,
    color: 'var(--text-secondary)',
    bgGradient: 'var(--bg-surface)',
    icon: '📐',
  },
  {
    id: 'pro',
    name: 'Pro 会员',
    subtitle: '支持开发者',
    price: 19,
    period: '/月',
    description: '解锁高级学习工具 · 无限额度',
    highlight: '不是买答案，是支持产品持续开发',
    features: [
      { text: '无限额度', detail: '取消每日题目限制', star: true },
      { text: '高级教师模式', detail: '自动讲课 · 自动播放步骤 · 自动高亮重点 · 自动生成讲稿', star: true },
      { text: 'PPT 课件导出', detail: '一键生成课堂 PPT' },
      { text: 'PDF 讲义导出', detail: '精美排版讲义' },
      { text: '高清图片导出', detail: '2x 分辨率截图' },
      { text: '错题本', detail: '自动收集 · 分类管理 · 收藏题目', star: true },
      { text: '学习分析', detail: '学习时长 · 薄弱环节 · 掌握度统计', star: true },
      { text: '高级分享', detail: '分享完整工作台 · 3D 场景 · 教师讲解模式' },
      { text: '云端同步', detail: '多设备历史记录同步' },
    ],
    limitations: [],
    cta: '升级 Pro',
    popular: true,
    color: 'var(--accent)',
    bgGradient: 'linear-gradient(135deg, rgba(99,102,241,0.06) 0%, rgba(139,92,246,0.04) 100%)',
    icon: '⭐',
    stripePriceId: 'pro_monthly',
    stripeYearlyId: 'pro_yearly',
  },
  {
    id: 'teacher',
    name: '教师版',
    subtitle: '课堂教学工具',
    price: 29,
    period: '/月',
    description: 'Pro 全部功能 + 班级管理',
    highlight: '批量课件 · 学生管理 · 教学统计',
    features: [
      { text: 'Pro 全部功能', detail: '无限额度 + 所有高级工具' },
      { text: '班级管理', detail: '创建班级 · 邀请学生 · 批量管理', star: true },
      { text: '批量生成课件', detail: '一次生成全班讲义', star: true },
      { text: '批量导出 PPT', detail: '整章课件一键导出' },
      { text: '学生学习统计', detail: '全班学习数据仪表盘' },
      { text: '学生分析', detail: '个体薄弱点 · 进步曲线' },
      { text: '作业布置', detail: '在线布置 · 自动批改' },
    ],
    limitations: [],
    cta: '升级教师版',
    popular: false,
    color: 'var(--color-success)',
    bgGradient: 'linear-gradient(135deg, rgba(34,197,94,0.05) 0%, rgba(16,185,129,0.03) 100%)',
    icon: '🏫',
    stripePriceId: 'teacher_monthly',
    stripeYearlyId: 'teacher_yearly',
  },
]

export const GEOMETRY_NAMES = {
  cube: '正方体',
  sphere: '球体',
  cylinder: '圆柱体',
  cone: '圆锥体',
  pyramid: '棱锥',
  prism: '棱柱',
  squareFrustum: '四棱台',
  circularFrustum: '圆台',
  cuboid: '长方体',
  tetrahedron: '正四面体',
  octahedron: '正八面体',
}

export const SUBJECTS = [
  {
    id: 'math',
    name: '数学',
    shortName: '数',
    icon: 'math',
    color: '#4A90E2',
    gradient: 'linear-gradient(135deg, #4A90E2, #6BA3E8)',
    description: '立体几何、函数、代数',
    features: ['AI解析', '3D动态讲解', '分步解题', '错题本'],
    path: '/math',
  },
  {
    id: 'physics',
    name: '物理',
    shortName: '物',
    icon: 'physics',
    color: '#00B4D8',
    gradient: 'linear-gradient(135deg, #00B4D8, #0096C7)',
    description: '力学、电磁学，光学',
    features: ['模型识别', '公式推导', '受力分析', '图像分析'],
    path: '/physics',
  },
]
